apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: prisma
  namespace: prisma
  labels:
    component: prisma
spec:
  replicas: 1
  selector:
    matchLabels:
      component: prisma
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: prisma
    spec:
      containers:
        - name: "cloudsql-proxy"
          image: "gcr.io/cloudsql-docker/gce-proxy"
          imagePullPolicy: IfNotPresent
          resources: {}
          command: ["/cloud_sql_proxy",
                "-instances=calcium-land-257506:us-central1:demo-db-instance=tcp:5432",
                "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: "cloudsql-secrets-volume"
              mountPath: "/secrets/cloudsql"
              readOnly: true
        - name: prisma
          image: prismagraphql/prisma:1.34
          imagePullPolicy: IfNotPresent
          resources: {}
          ports:
          - containerPort: 4466
            protocol: TCP
          env:
            - name: PRISMA_CONFIG
              valueFrom:
                secretKeyRef:
                  name: prisma-config-secret
                  key: PRISMA_CONFIG
      volumes:
        - name: "cloudsql-secrets-volume"
          secret:
            secretName: "cloudsql-credentials"